/*
 * File: app/view/Buttons.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Viewer.view.Buttons', {
    extend: 'Ext.container.Container',
    alias: 'widget.buttons',

    requires: [
        'Viewer.view.ButtonsViewModel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'buttons'
    },

    items: [
        {
            xtype: 'button',
            handler: function(button, e) {
                function handler(response, event) {
                    if (event.status) {
                        //success
                        Ext.Msg.alert(
                        'Success',
                        'Test message has been enqueued. <br />Submitted Job Id: ' + response
                        ).setIcon(Ext.Msg.QUESTION);
                        button.enable();
                        //button.unmask(); //too dark since #818
                    } else {
                        //failure
                        Ext.Msg.alert(
                        'Error enqueueing test message',
                        event.message
                        ).setIcon(Ext.Msg.ERROR);
                    }
                }

                button.disable();
                //button.mask(); //too dark since #818

                Visualforce.remoting.Manager.invokeAction(
                $RemoteAction.ApexClassSummaryExtension.enqueue,
                Id,
                handler
                );
            },
            text: 'Enqueue Test Event'
        }
    ]

});