/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    views: [
        'Buttons'
    ],
    name: 'Viewer',

    launch: function() {
        //http://www.sencha.com/forum/showthread.php?296173-validIdRe-throwing-Invalid-Element-quot-id-quot-for-valid-ids-containing-colons&p=1081456#post1081456
        Ext.dom.Element.prototype.validIdRe = /^[a-z_][:a-z0-9\-_]*$/i;

        Ext.create('Viewer.view.Buttons', {
            renderTo: $Component.pageBlockButtonsId
        });
    }

});
